// Writes .env.localdb from the running local Supabase stack (`npm run db:local:start` calls this).
// Existing app JWT secrets in the file are kept so local sessions survive a re-run.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const OUT = ".env.localdb";

function parseEnv(text) {
  const vars = {};
  for (const line of text.split("\n")) {
    const match = /^([A-Z0-9_]+)=(?:"(.*)"|'(.*)'|(.*))$/.exec(line.trim());
    if (match) vars[match[1]] = match[2] ?? match[3] ?? match[4];
  }
  return vars;
}

let status;
try {
  status = parseEnv(execFileSync("npx", ["supabase", "status", "-o", "env"], { encoding: "utf8" }));
} catch {
  console.error("Local Supabase isn't running. Start it with `npm run db:local:start`.");
  process.exit(1);
}

for (const key of ["API_URL", "DB_URL", "PUBLISHABLE_KEY", "SECRET_KEY"]) {
  if (!status[key]) {
    console.error(`\`supabase status\` did not report ${key}; is the stack fully started?`);
    process.exit(1);
  }
}

const SIGNING_KEYS = "supabase/signing_keys.json";
if (!existsSync(SIGNING_KEYS)) {
  console.error(`Missing ${SIGNING_KEYS}; run \`npm run db:local:start\` to create it.`);
  process.exit(1);
}
// Same key the local stack signs with (config.toml signing_keys_path), so our Realtime tokens verify.
const signingKey = JSON.stringify(JSON.parse(readFileSync(SIGNING_KEYS, "utf8"))[0]);

const previous = existsSync(OUT) ? parseEnv(readFileSync(OUT, "utf8")) : {};
const secret = (key) => previous[key] || randomBytes(32).toString("hex");

const env = {
  DATABASE_URL: status.DB_URL,
  DIRECT_URL: status.DB_URL,
  JWT_ACCESS_SECRET: secret("JWT_ACCESS_SECRET"),
  JWT_REFRESH_SECRET: secret("JWT_REFRESH_SECRET"),
  SUPABASE_URL: status.API_URL,
  SUPABASE_SECRET_KEY: status.SECRET_KEY,
  SUPABASE_JWT_SIGNING_KEY: signingKey,
  VITE_SUPABASE_URL: status.API_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY: status.PUBLISHABLE_KEY,
  VITE_DEMO_TOOLS: "true",
};

writeFileSync(
  OUT,
  `# Generated by scripts/local-env.mjs for the local Supabase stack. Safe to delete and regenerate.\n` +
    Object.entries(env)
      .map(([key, value]) => `${key}='${value}'`)
      .join("\n") +
    "\n",
);
console.log(`Wrote ${OUT} (Studio: ${status.STUDIO_URL ?? "http://127.0.0.1:54323"})`);
